### ISSUE TITLE
Enhance: gulp sass / gulp babelを指定してignore

### ISSUE THREAD

**Issue by W-Kentaro** [yama-dev/dev-template-gulp#32]
コンパイルするsass、jsファイルが増えすぎると時間がかかりすぎるので、
現在実装中の要素だけ開発中はコンパイルしたい。
管理しやすいように外部jsonファイル等で管理を想定。

可能であれば、
releaseコマンド時にignoreファイルが残っていたらエラー文を吐き出すようにする。

**Comment by yama-dev** [comment]
いただいた方法ではないのですが…

外部jsonファイルではなく、差分監視用のgulp-progenyを導入して差分ビルドを実現しています。
https://github.com/HerringtonDarkholme/gulp-progeny
#37
